### ISSUE TITLE
Run main.py got | ERROR    | __main__:init_accounts:619 - Error init wallet: pop from empty list

### ISSUE THREAD

**Issue by ShmilyGone** [854771076/Plume_TestNet_Bot#1]
Hi, I tried to run python main.py but got this error: 
 | ERROR    | __main__:init_accounts:619 - Error init wallet: pop from empty list
 How to fix this?

**Comment by 854771076** [comment]
> Hi, I tried to run python main.py but got this error: 
>  | ERROR    | __main__:init_accounts:619 - Error init wallet: pop from empty list
>  How to fix this?

Because I used an IP proxy interface, your IP is not on the whitelist. You can rewrite the code to change the proxy IP service address to your own

**Comment by 854771076** [comment]
If you feel that this project is helpful to you or requires technical support, please give a reward of 0x72691a36ed1fac3b197fb42612dc15a8958bf9f2
